[server]
headless = true
port = 8501
address = "0.0.0.0"

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[logger]
level = "debug"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"